### ISSUE TITLE
[Suggestion] iCal event with URL to avoid signup

### ISSUE THREAD

**Issue by hernil** [aslakhol/shera#62]
From the latest newsletter: 
>Say I invite you to my birthday party. I send you a handy link that has all the info you need. 2 weeks later you’re getting ready to head to my place, and big shocker to no-one not named Aslak, you’ve forgotten what that damn link was. You might remember Shera, but unless you are lucky with your browser history you won’t find the full link. In the end you still have to scroll back up in the chat to find the get the info you need. 
>
> I really liked not having to make an account to attend, but Shera didn’t work if you had to remember some random URL. So, now you have to sign in to attend. It’s a bit sad, but at least it’s quick and easy, and it does allow me to build more useful features in the future. 

If the event at the end of the URL has an iCal that can easily be added to your calendar containing the event URL then you won't have to remember anything. Today's default is probably fine for most but a lot of people (especially those of us fleeing Facebook and the like) do have somewhat of an account and signup fatigue that might just raise the barrier of entry enough to skip the service entirely. So a "just get this event in my calendar, I'll be a big boy and check for updates myself" mode would be cool 😄 

(this specific mode of operation was suggested by a third party who prefers to remain anonymous)

**Comment by aslakhol** [comment]
Good suggestion! I've got ICal on my todo-list already and I'll consider if that might negate the need for the reminders. I'm not 100% convinced it'll be "good enough", but for some users it would totally be enough. I've already got a button to add to your google calendar (because that was super fast to do) and as long as you use google calendar you can do this today. Just hit the calendar icon button, no need to sign up. 

And obviously when you've got google calendar singup it makes sense to get the generic option up and running as well!
