### ISSUE TITLE
[Suggestion][UX/UI] : Sort/filter options for "Events"

### ISSUE THREAD

**Issue by mariebmo** [aslakhol/shera#93]
It would be great to have an option to filter/sort options for the "events"-view. 

Filters:
- My events
- Events hosted by <name>
- Attending/Maybe/Unanswered

Sorting:
- by date
- most recent

It'd also be great to show past events!

**Comment by aslakhol** [comment]
It currently shows past events, but it displays them in the same list. I certainly need to split those lists, so that you can see them separately.

**Comment by aslakhol** [comment]
When it comes to filters and custom sorting I don't think people have that many "active" events at a time. So I don't think we need all that functionality right away. However, I have been thinking about other ways to organize events. I like the ideas of having different "feeds". So that an organization could have their feed for their events, you could decide to publish or not to your private / public feed and maybe there would be a feed for a city or location.
